Revert "Include the dynamic-import package in new apps and packages."
Partially reverts commit 8364f813448bfd10457e63fe3a22d0142d248cd5.

This commit was causing self-test failures like the following:

  While selecting package versions:
  error: unknown package in top-level dependencies: dynamic-import

I suspect these tests won't work until the dynamic-import package is
published with a non-prerelease version.