Fix failure for local packages to depend on built
Bug introduced in 0.9.4. This only seems to occur in some contexts; a
way to consistently reproduce is:

  $ rm -rf packages/test-in-browser/.build.test-in-browser && curmeteor test-packages
  [[[[[ Tests ]]]]]

  => Started proxy.
  => Started MongoDB.
  => Errors prevented startup:

  While Building package `test-in-browser`:
  error: package not available: bootstrap