Better "unknown package" errors
Inspired by how I always forget to change the `api.use` in `onTest` when
I rename a package.

Now I get:

```
error: unknown package: test-package
Required by: local-test:david:test-package 0.0.1
```

Yay!