Avoid duplicate Version Solver conflict errors
such as:

    While selecting package versions:
    error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_1.
    Constraints on package "less":
    * less@=2.5.0_1 <- top level
    * less@1.0.11 <- multiply:iron-router-progress 1.0.1
    * less@1.0.11 <- zhenya:debug 0.0.2

    Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_1.
    Constraints on package "less":
    * less@=2.5.0_1 <- top level
    * less@1.0.11 <- multiply:iron-router-progress 1.0.1
    * less@1.0.11 <- zhenya:debug 0.0.2